<?php

function core_theme_portal_enqueue_react_app()
{
    // Exit early in admin area (we only need React on the frontend)
    if (is_admin())
        return;

    // Get the current page template file name
    $template = get_page_template_slug(get_queried_object_id());

    // Only enqueue React app if the page uses the "template-portal.php" template
    if ($template === 'template-portal.php') {

        // Path to asset manifest generated by React build (contains hashed file names)
        $manifest_path = get_template_directory() . '/app/build/asset-manifest.json';
        if (!file_exists($manifest_path))
            return;

        // Decode manifest to get main JS and CSS file paths
        $manifest = json_decode(file_get_contents($manifest_path), true);
        $js = $manifest['files']['main.js'] ?? '';
        $css = $manifest['files']['main.css'] ?? '';

        // Enqueue React JavaScript bundle
        if ($js) {
            wp_enqueue_script(
                'react-app',
                $js,
                [],
                null,
                true // load in footer
            );
        }

        // Enqueue React CSS
        if ($css) {
            wp_enqueue_style(
                'react-style',
                $css
            );
        }

        // Inject React mount point at the bottom of the page
        // add_action('wp_footer', function () {
        //     echo '<div id="root"></div>';
        // });
    }
}
add_action('wp_enqueue_scripts', 'core_theme_portal_enqueue_react_app');