import {
  Activity,
  BarChart3,
  BookOpen,
  Bookmark,
  Briefcase,
  Calculator,
  Calendar,
  CalendarDays,
  CheckCircle,
  Clock,
  Contact,
  DollarSign,
  Dumbbell,
  ExternalLink,
  FileText,
  PieChart,
  Settings,
  Users,
} from 'lucide-react';

export const toolCategories = [
  {
    title: 'Work Management',
    tools: [
      {
        name: 'Client Manager',
        description: 'Manage client information and project details',
        icon: Users,
        status: 'active',
        color: 'bg-orange-500',
        link: '/clients',
      },
      {
        name: 'Project Scheduler',
        description: 'Schedule and manage project deadlines',
        icon: Calendar,
        status: 'active',
        color: 'bg-indigo-500',
        link: '/projects',
      },
      {
        name: 'Task Tracker',
        description: 'Track time spent on different projects and tasks',
        icon: Clock,
        status: 'active',
        color: 'bg-green-500',
        link: '/tasks',
      },
      {
        name: 'Estimation',
        description: 'Calculate project costs and profit margins',
        icon: Calculator,
        status: 'active',
        color: 'bg-purple-500',
        link: '/estimations',
      },
      {
        name: 'Project Reports',
        description: 'Generate and review detailed project reports',
        icon: FileText,
        status: 'active',
        color: 'bg-indigo-500',
        link: '/project-reports',
      },
    ],
  },
  {
    title: 'Documents',
    tools: [
      {
        name: 'Resume Builder',
        description: 'Create and manage professional resumes',
        icon: Briefcase,
        status: 'active',
        color: 'bg-emerald-500',
        link: '/resume',
      },
    ],
  },
  {
    title: 'Network',
    tools: [
      {
        name: 'Leader',
        description: 'Manage your professional network and connections',
        icon: Contact,
        status: 'active',
        color: 'bg-cyan-500',
        link: '/leader',
      },
    ],
  },
  {
    title: 'Business Tools',
    tools: [
      {
        name: 'Invoice Generator',
        description: 'Create and manage professional invoices for clients',
        icon: FileText,
        status: 'coming-soon',
        color: 'bg-blue-500',
        link: '#',
      },
      {
        name: 'Revenue Dashboard',
        description: 'Track earnings and financial performance',
        icon: DollarSign,
        status: 'coming-soon',
        color: 'bg-emerald-500',
        link: '#',
      },
      {
        name: 'Analytics Hub',
        description: 'Analyze productivity and business metrics',
        icon: BarChart3,
        status: 'coming-soon',
        color: 'bg-pink-500',
        link: '#',
      },
    ],
  },
  {
    title: 'Personal',
    tools: [
      {
        name: 'Todo Manager',
        description: 'Manage personal tasks and daily activities',
        icon: CheckCircle,
        status: 'active',
        color: 'bg-teal-500',
        link: '/todos',
      },
      {
        name: 'Quick Links',
        description: 'Save blog posts and articles to read later',
        icon: ExternalLink,
        status: 'active',
        color: 'bg-indigo-500',
        link: '/quick-links',
      },
      {
        name: 'Bookmark Manager',
        description: 'Save and organize your favorite websites and resources',
        icon: Bookmark,
        status: 'active',
        color: 'bg-violet-500',
        link: '/bookmarks',
      },
      {
        name: 'Habit Manager',
        description: 'Track daily habits and build consistent routines',
        icon: Calendar,
        status: 'active',
        color: 'bg-emerald-500',
        link: '/habits',
      },
      {
        name: 'Workout Manager',
        description: 'Track exercises, sets, and workout progress',
        icon: Dumbbell,
        status: 'active',
        color: 'bg-red-500',
        link: '/workouts',
      },
      {
        name: 'Journal',
        description: 'Capture daily thoughts, reflections, and moments',
        icon: BookOpen,
        status: 'active',
        color: 'bg-indigo-600',
        link: '/journal',
      },
      {
        name: 'Planner',
        description:
          'Organize your schedule, tasks, and priorities effectively',
        icon: CalendarDays,
        status: 'active',
        color: 'bg-cyan-600',
        link: '/plan',
      },
    ],
  },
  {
    title: 'Finance Tools',
    tools: [
      {
        name: 'Income Tracker',
        description: 'Track and analyze your income streams effectively',
        icon: DollarSign,
        status: 'active',
        color: 'bg-green-500',
        link: '/income',
      },
      {
        name: 'Finance Management',
        description: 'Plan expenses and track spending with flexible periods',
        icon: PieChart,
        status: 'active',
        color: 'bg-emerald-600',
        link: '/finance',
      },
    ],
  },
  {
    title: 'System',
    tools: [
      {
        name: 'Activity Overview',
        description: 'Track your daily productivity and progress',
        icon: Activity,
        status: 'active',
        color: 'bg-cyan-500',
        link: '/activity',
      },
      {
        name: 'Settings Panel',
        description: 'Configure portal settings and preferences',
        icon: Settings,
        status: 'active',
        color: 'bg-gray-500',
        link: '/settings',
      },
    ],
  },
];
