export const propertyTemplates = [
  {
    type: 'residential',
    items: [
      {
        id: 1,
        name: 'Small House',
        description: 'A cozy starter home perfect for new residents',
        cost: 1000,
        income: 50,
        maintenanceCost: 10,
        requiredLevel: 1,
      },
      {
        id: 2,
        name: 'Family Home',
        description: 'A comfortable home with room for growth',
        cost: 2500,
        income: 100,
        maintenanceCost: 25,
        requiredLevel: 3,
      },
      {
        id: 3,
        name: 'Luxury Villa',
        description: 'An upscale residence with premium amenities',
        cost: 5000,
        income: 250,
        maintenanceCost: 75,
        requiredLevel: 5,
      },
    ],
  },
  {
    type: 'commercial',
    items: [
      {
        id: 4,
        name: 'Small Shop',
        description: 'A modest retail space for small businesses',
        cost: 1500,
        income: 75,
        maintenanceCost: 15,
        requiredLevel: 2,
      },
      {
        id: 5,
        name: 'Restaurant',
        description: 'A popular dining establishment',
        cost: 3000,
        income: 150,
        maintenanceCost: 40,
        requiredLevel: 4,
      },
      {
        id: 6,
        name: 'Shopping Mall',
        description: 'A large retail complex with multiple stores',
        cost: 7500,
        income: 400,
        maintenanceCost: 100,
        requiredLevel: 6,
      },
    ],
  },
  {
    type: 'industrial',
    items: [
      {
        id: 7,
        name: 'Workshop',
        description: 'A small manufacturing facility',
        cost: 2000,
        income: 100,
        maintenanceCost: 25,
        requiredLevel: 2,
      },
      {
        id: 8,
        name: 'Factory',
        description: 'A medium-sized production facility',
        cost: 4000,
        income: 200,
        maintenanceCost: 60,
        requiredLevel: 4,
      },
      {
        id: 9,
        name: 'Industrial Complex',
        description: 'A large-scale manufacturing hub',
        cost: 10000,
        income: 500,
        maintenanceCost: 150,
        requiredLevel: 7,
      },
    ],
  },
];
